remote: [false]


experienceLevel:
 internship: [false]
 entry: [true]
 associate: [true]
 mid-senior level: [true]
 director: [false]
 executive: [false]

jobTypes:
 full-time: [true]
 contract: [true]
 part-time: [false]
 temporary: [true]
 internship: [false]
 other: [false]
 volunteer: [false]

date:
 all time: [true]
 month: [true]
 week: [true]
 24 hours: [true]

positions:
  - Reseach Associate
  - Research Scientist
  - Senior research associate
  - Research Technician

locations:
  - United States of America
  - USA
  - United states

distance: 100

companyBlacklist:
  - Thermofisher

titleBlacklist:
  - Computer engineering
  - Bioinformatics
